services:
  nginx:
    build:
      context: ../..
      dockerfile: docs/docker/Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - sky_nginx_conf:/etc/nginx/nginx.conf
      - sky_nginx_conf_dir:/etc/nginx/conf.d
      - sky_nginx_html:/usr/share/nginx/html
      - sky_nginx_contrib:/etc/nginx/contrib
    network_mode: ${NETWORK_MODE}
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - sky_mysql_data:/var/lib/mysql
      - ${INIT_SQL}:/docker-entrypoint-initdb.d/init.sql
      - ${MYSQL_CONF}:/etc/mysql/conf.d/my.cnf
    network_mode: sky-take-out
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - sky_redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    network_mode: ${NETWORK_MODE}
networks:
  sky-take-out:
    name: sky-take-out
volumes:
  sky_mysql_data:
    name: sky_mysql_data
  sky_nginx_conf:
    name: sky_nginx_conf
  sky_nginx_conf_dir:
    name: sky_nginx_conf_dir
  sky_nginx_html:
    name: sky_nginx_html
  sky_nginx_contrib:
    name: sky_nginx_contrib
  sky_redis_data:
    name: sky_redis_data
