server:
  port: 8080

spring:
  application:
    name: sky-take-out
  profiles:
    active: dev
  main:
    allow-circular-references: true
    banner-mode: off
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现
    map-underscore-to-camel-case: true # 下划线到驼峰的映射
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto # 主键类型
      logic-delete-value: 0 # 逻辑删除值
      logic-not-delete-value: 1 # 逻辑未删除值
    banner: off # 是否打印mybatis-plus的banner
logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

knife4j:
  enable: true
  openapi:
    title: 苍穹外卖项目接口文档
    description: "苍穹外卖项目接口文档"
    concat: 我
    version: v2.0
    group:
      sky:
        group-name: sky
        api-rule: package
        api-rule-resources:
          - com.sky.controller

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: sky-take-out_admin
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: sky-take-out_user
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}