services:
  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx/nginx.conf
      - nginx_conf_dir:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_contrib:/etc/nginx/contrib
    network_mode: ${NETWORK_MODE}

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ${INIT_SQL}:/docker-entrypoint-initdb.d/init.sql
    network_mode: ${NETWORK_MODE}

networks:
  ${NETWORK_NAME}:
volumes:
  mysql_data:
  nginx_conf:
  nginx_conf_dir:
  nginx_html:
  nginx_contrib: